FROM buildpack-deps:{{ env.codename }}-curl

RUN set -eux; \
	apt-get update; \
	apt-get install -y --no-install-recommends \
{{
if [
	"focal", "groovy"
] | index(env.codename) then (
-}}
		bzr \
{{ ) else "" end -}}
		git \
		mercurial \
		openssh-client \
		subversion \
		\
# procps is very common in build systems, and is a reasonably small package
		procps \
	; \
	rm -rf /var/lib/apt/lists/*
